### ISSUE TITLE
Getting Error messages in "APM Server1 log" as soon as a request is made

### ISSUE THREAD

**Issue by deepamshah20** [rafal-szypulka/grafana-ibm-apm#1]
hi, 
I am seeing a few ERROR messages in the server1 log of APM after enabling this configuration. 

[6/14/17 17:14:38:967 AEST] 0002d6de com.ibm.tivoli.rest                                          E ##### The referer field does not exist in the HTTP request.  The lack of a referer field could be considered a CSRF attack when the request is performing a state change.null
[6/14/17 17:14:38:968 AEST] 0002d6de ibm.tivoli.monitoring.provider.metrics.MetricsGaianCollector I *************collection request without refId received.
[6/14/17 17:14:38:975 AEST] 0002d70f com.ibm.tivoli.rest                                          E ##### The referer field does not exist in the HTTP request.  The lack of a referer field could be considered a CSRF attack when the request is performing a state change.null

FYI -  since my  APM on prem is over https,  I had to use  https://<server>:8091/   instead of http://<server:8090> 

Also,  Yes I have enabled the "nginx" proxy. Without having it, it was showing errors to even connect to the data source. 

Thanks

**Comment by rafal-szypulka** [comment]
Hi, I can only confirm that your findings are correct. Most probably one of the interim fixes to APM 8.1.3 introduced a new security check for API requests and it rejects API calls if hostname:port part of the referer http header is different than the request. GA version of APM 8.1.3 and ITM 6.x doesn't have this check. If the referer field is empty, it works but the error is logged. In our case, referer is different than request because Grafana proxies API requests (which is IMO good from the security point of view). I will try to address this issue with IBM APM development, but can't guarantee if and when it will be solved.

**Comment by deepamshah20** [comment]
Hi Rafal

No worries at all. Thanks for the response.

My plan is to just use this in a Dev Environment for the next 1-ish months – until the time APM Team releases 8.1.4 with the new Dashboard capability. Hence, there’s no real urgent need and as you said, the messages are just logged but the queries still work and hence it is fine.  I am just a little hesitant at putting this in PROD as I don’t really want to impact anything in prod. I might consider depending on my user’s requirement ☺

I must say that it was really great to get this plugin and at-least my users can see some detailed data urgently if needed in the next two months.  FYI – I couldn’t get it to connect to  ITM yet (I am sure I am making a mistake somewhere and hence it isn’t working .. but anyway. )

Thanks very much for building this – it definitely will be helpful.



Regards,
Deepam Shah I  IT Systems Management Specialist | Technology Solutions & Services - Operations
Bendigo and Adelaide Bank I The Bendigo Centre I PO Box 480 I Bendigo VIC 3552
P: +613 5485 6980 I M: +61 430 273 233 | F: +613 5485 7622 I E: deepam.shah@bendigoadelaide.com.au<mailto:deepam.shah@bendigoadelaide.com.au>
