### ISSUE TITLE
Query in dashboard's variable returns nothing

### ISSUE THREAD

**Issue by SoldatovAV** [rafal-szypulka/grafana-ibm-apm#22]
Hi
Grafana version: 5.3.4
IBM APM datasource version: 0.8.0 (grafana-cli)
OS are you running grafana on: Centos 7.5

I added a variable to the dashboard settings to get a list of Windows OS (NT) agents, but the query (TMSAgent.%IBM.STATIC021) returns nothing.

request:
GET /api/datasources/proxy/6/datasources/TMSAgent.%25IBM.STATIC021/datasets/msys/items?properties=all HTTP/1.1

response:
{"items":[],"filteredRows":0,"identifier":"id","totalRows":0,"numRows":0}

**Comment by rafal-szypulka** [comment]
Hi, try to run the similar request in ITMRESTProvider UI as described in https://github.com/rafal-szypulka/grafana-ibm-apm#troubleshooting and check if you can see Windows agents instances in json response.

**Comment by rafal-szypulka** [comment]
It looks the source of the problem is on ITM side. `TMSAgent.%IBM.STATIC021` as variable definition looks fine (plugin does URL encode to `TMSAgent.%25IBM.STATIC021`). I would suggest to open a ticket with ITM support. You may also check the TEPS eWAS SystemOut.log after executing mentioned request in the ITMRESTProvider UI.

**Comment by rafal-szypulka** [comment]
This issue has been closed because it has been inactive for a long time.
