### ISSUE TITLE
Issue with 0.9 IBM APM

### ISSUE THREAD

**Issue by romulolibralon** [rafal-szypulka/grafana-ibm-apm#31]
Please include this information:

- What Grafana version are you using?
6.7
- What IBM APM datasource version are you using and how you installed it (git clone/downloaded git release/grafana-cli) ?
Both
- What OS are you running grafana on?
Rhel7
- What did you do?
Configure the Datasource to create some dashboards
- What was the expected result?
More faster
- What happened instead?
Too slow to get the data 
- If related to metric query / query editor:
Any metric
Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by rafal-szypulka** [comment]
I don't think that slow performance comes from the Grafana or IBM APM Grafana plugin. Install Grafana server on the TEPS server or in the local network and access Grafana UI via fast network connection. Do not select more than 24h time range. If you need to query long time ranges and need better Grafana performance then [itm_exporter](https://github.com/rafal-szypulka/itm_exporter) and Prometheus may be a better solution for you. Also, read the [Troubleshooting](https://github.com/rafal-szypulka/grafana-ibm-apm/blob/master/troubleshooting.md) section and execute a similar request in the ITMRESTProvider web app in order to compare Grafana performance and direct ITM REST API request performance. If you see memory issues in TEPS eWAS logs, increase heap size: https://www.ibm.com/support/pages/resolving-teps-ewas-memory-issues-increasing-jvm-heap-size
