### ISSUE TITLE
RDB TOP_SQL do not available on Attribute Group

### ISSUE THREAD

**Issue by dannemca** [rafal-szypulka/grafana-ibm-apm#5]
I have successful configured this APM API as dataset to my Grafana server, dashboards do show data from my APM Agents, including those which I have configured from your examples here on this project.

First of all, thanks for this master piece.

The issue I am facing is, I am not able to see all possibles Attributes for some Agents type, most specifically for RDB Agents. I need to create a dashboard with the TOP_SQL attribute group, but it is not available on the dataset.

From rest I am able to see it:
/ibm/tivoli/rest/providers/itm.KD8/datasources/TMSAgent.%25IBM.OracleAgentRDB/datasets/MetricGroup.KRZTOPSQL

Is some limitation or pre-configured attributes you have set for this? Or does it should get all attributes by default?

I have noted that this same attribute is not available on APM Dashboard it self, is there any relation?

Thanks.

**Comment by rafal-szypulka** [comment]
Hi, 
Attribute group list per agent type is created dynamically via API call.
Attribute groups not collected in APM8 prefetch database are filtered out, so thats why you see only subset of attribute groups.
Attribute groups are filtered out based on requests similar to: /ibm/tivoli/rest/providers/itm.KD8/datasources/TMSAgent.%25IBM.OracleAgentRDB/datasets
(please check the results of this URI if you can),
if particular dataset (attribute group) property notAvailableInPreFetch=true, then attribute group is filtered out by the plugin, because API call response would be empty anyway.
TOP_SQL is probably one of the attribute groups not collected by APM.

I think this is also the reason you don't see results of this query in APM Dashboard. Please check with IBM Support to make sure. 

Plugin currently can query only numeric attributes.

**Comment by dannemca** [comment]
Got it.

      {
         "datasourceId": "TMSAgent.%IBM.OracleAgentRDB",
         "description": "KRZ_RDB_TOP_SQL",
         "id": "MetricGroup.KRZTOPSQL",
         "itemsUri": "\/providers\/itm.KD8\/datasources\/TMSAgent.%25IBM.OracleAgentRDB\/datasets\/MetricGroup.KRZTOPSQL\/items",
         "label": "KRZ_RDB_TOP_SQL",
         "notAvailableInPreFetch": true,
         "providerId": "itm.KD8",
         "type": "MetricGroup",
         "uri": "\/providers\/itm.KD8\/datasources\/TMSAgent.%25IBM.OracleAgentRDB\/datasets\/MetricGroup.KRZTOPSQL"
      },

It is set as true, so that's why no displayed on your pluing, and also, that's why I can see no data on Jazz as well.

You helped me out to find out two issues at same.

Thanks, rafal-szypulka.
